# Generated by Django 6.0.3 on 2026-04-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('Codigo', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.TextField(max_length=20)),
                ('Precio', models.FloatField()),
                ('Cantidad', models.IntegerField()),
                ('Descripcion', models.TextField(max_length=50)),
                ('Fecha', models.DateField()),
                ('Categoria', models.TextField(max_length=50)),
                ('imagen', models.ImageField(null=True, upload_to='Productos')),
            ],
        ),
    ]
